<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <VivariumVersionBase>0.1</VivariumVersionBase>
    <VersionPrefix>$(VivariumVersionBase).0</VersionPrefix>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
</Project>
