<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.0" />
    <PackageReference Include="NUnit" Version="4.3.2" />
    <PackageReference Include="NUnit.Analyzers" Version="4.7.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Vivarium.Cli\Vivarium.Cli.csproj" />
    <ProjectReference Include="..\..\src\Vivarium.Controller\Vivarium.Controller.csproj" />
    <ProjectReference Include="..\..\src\Vivarium.Agent\Vivarium.Agent.csproj" />
    <ProjectReference Include="..\..\src\Vivarium.Bootstrap\Vivarium.Bootstrap.csproj"
                      ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\..\src\Vivarium.Contracts\Vivarium.Contracts.csproj" />
  </ItemGroup>

</Project>
